repos:
  # JavaScript/TypeScript
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npx eslint --fix
        language: system
        files: \.(js|jsx|ts|tsx)$
        pass_filenames: true

  # TypeScript type checking
  - repo: local
    hooks:
      - id: typecheck
        name: TypeScript Type Check
        entry: npx tsc --noEmit
        language: system
        pass_filenames: false
        files: \.(ts|tsx)$